// Generated by scripts/portal-types.ts from executed PostgreSQL migrations.
// HTTP/Auth provider integration is verified separately. Do not edit manually.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
export interface Database {
  public: {
    Tables: Record<never, never>;
    Views: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
    Functions: {
      approve_and_queue_release: {
        Args: { p_release: string; p_digest: string };
        Returns: string;
      };
      auth_cleanup: { Args: {}; Returns: undefined };
      auth_record_send: {
        Args: { p_key: string; p_outcome: string };
        Returns: undefined;
      };
      auth_request_reserve: {
        Args: {
          p_key: string;
          p_email: string;
          p_email_hash: string;
          p_network_hash: string;
          p_origin: string;
          p_mode: string;
          p_actor: string;
        };
        Returns: Json;
      };
      auth_resend_recipient: { Args: { p_user: string }; Returns: Json };
      auth_verify_claim: {
        Args: { p_key: string; p_origin: string; p_network_hash: string };
        Returns: Json;
      };
      auth_verify_finish: {
        Args: {
          p_key: string;
          p_claim: string;
          p_user: string;
          p_success: boolean;
          p_uncertain: boolean;
        };
        Returns: boolean;
      };
      authorise_job_dispatch: { Args: { p_job: string }; Returns: Json };
      before_participant_created: { Args: { event: Json }; Returns: Json };
      begin_provisioning: {
        Args: { p_request: string; p_project: string; p_email: string };
        Returns: Json;
      };
      create_project: {
        Args: {
          p_request: string;
          p_public_id: string;
          p_title: string;
          p_maker: string;
          p_theme: string;
        };
        Returns: string;
      };
      decide_revision: {
        Args: {
          p_revision: string;
          p_digest: string;
          p_expected_version: number;
          p_decision: string;
          p_feedback: string;
          p_note: string;
        };
        Returns: number;
      };
      get_event_administration: { Args: {}; Returns: Json };
      get_my_projects: { Args: {}; Returns: Json };
      get_people: { Args: {}; Returns: Json };
      get_project_draft: { Args: { p_project: string }; Returns: Json };
      get_releases: { Args: {}; Returns: Json };
      get_review_queue: { Args: {}; Returns: Json };
      get_revision_preview: { Args: { p_revision: string }; Returns: Json };
      invitation_receipt: { Args: { p_request: string }; Returns: boolean };
      portal_context: { Args: {}; Returns: Json };
      portal_storage_access: {
        Args: { bucket: string; obj: string; writing: boolean };
        Returns: boolean;
      };
      prepare_release: {
        Args: { p_source_commit: string; p_revisions: string[] };
        Returns: Json;
      };
      record_event_config: {
        Args: { p_expected_version: number; p_config: Json; p_themes: Json };
        Returns: number;
      };
      register_reviewed_source: {
        Args: { p_commit: string };
        Returns: undefined;
      };
      reserve_upload: {
        Args: { p_project: string; p_type: string; p_bytes: number };
        Returns: Json;
      };
      retry_job: { Args: { p_job: string }; Returns: undefined };
      revoke_asset: { Args: { p_asset: string }; Returns: undefined };
      save_project_draft: {
        Args: { p_project: string; p_expected_version: number; p_fields: Json };
        Returns: Json;
      };
      set_editing_open: { Args: { p_open: boolean }; Returns: undefined };
      set_event_role: {
        Args: { p_user: string; p_role: string; p_active: boolean };
        Returns: undefined;
      };
      set_membership: {
        Args: { p_project: string; p_user: string; p_active: boolean };
        Returns: undefined;
      };
      set_project_exclusion: {
        Args: { p_project: string; p_withdrawn: boolean };
        Returns: undefined;
      };
      submit_project_revision: {
        Args: {
          p_project: string;
          p_expected_version: number;
          p_request: string;
        };
        Returns: Json;
      };
      update_project_metadata: {
        Args: { p_project: string; p_expected_version: number; p_fields: Json };
        Returns: number;
      };
      worker_activation_check: {
        Args: { p_job: string; p_attempt: string };
        Returns: undefined;
      };
      worker_claim: { Args: { p_job: string; p_run: string }; Returns: Json };
      worker_cleanup_inventory: { Args: {}; Returns: Json };
      worker_environment: { Args: {}; Returns: Json };
      worker_fail: {
        Args: {
          p_job: string;
          p_attempt: string;
          p_code: string;
          p_activation_possible: boolean;
        };
        Returns: undefined;
      };
      worker_finish_provisioning: {
        Args: { p_request: string; p_user: string };
        Returns: undefined;
      };
      worker_heartbeat: {
        Args: { p_job: string; p_attempt: string };
        Returns: undefined;
      };
      worker_prepare: {
        Args: {
          p_job: string;
          p_attempt: string;
          p_snapshot: Json;
          p_digest: string;
          p_media: Json;
          p_commit: string;
        };
        Returns: undefined;
      };
      worker_queued: { Args: {}; Returns: Json };
      worker_reconcile: { Args: {}; Returns: Json };
      worker_record_deployment: {
        Args: { p_job: string; p_attempt: string; p_receipt: Json };
        Returns: undefined;
      };
      worker_record_invitation: {
        Args: { p_request: string };
        Returns: undefined;
      };
      worker_recovery_unlock: {
        Args: { p_job: string; p_attempt: string; p_receipt: Json };
        Returns: undefined;
      };
      worker_seed_local: {
        Args: {
          p_event: Json;
          p_themes: Json;
          p_projects: Json;
          p_owner: string;
          p_source: string;
        };
        Returns: undefined;
      };
      worker_subject: {
        Args: { p_job: string; p_attempt: string };
        Returns: Json;
      };
      worker_verified: {
        Args: {
          p_job: string;
          p_attempt: string;
          p_manifest_digest: string;
          p_receipt: Json;
        };
        Returns: undefined;
      };
    };
  };
}
