// Generate the RPC boundary from executable migration metadata, not hand-written
// guessed table types. Real Supabase gen-types remains a required integration check.
import { database } from '../tests/portal/database-harness.ts';
import { writeFile } from 'node:fs/promises';
const db = await database();
try {
  const result = await db.query<{
    name: string;
    names: string[];
    types: string[];
    result: string;
  }>(
    `select p.proname as name,p.proargnames as names,array(select format_type(t,null) from unnest(p.proargtypes::oid[]) t) as types,format_type(p.prorettype,null) as result from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' order by p.proname`,
  );
  const type = (t: string): string =>
    t === 'jsonb'
      ? 'Json'
      : t.endsWith('[]')
        ? `${type(t.slice(0, -2))}[]`
        : ['bigint', 'integer', 'numeric'].includes(t)
          ? 'number'
          : t === 'boolean'
            ? 'boolean'
            : t === 'void'
              ? 'undefined'
              : 'string';
  const output = `// Generated by scripts/portal-types.ts from executed PostgreSQL migrations.\n// HTTP/Auth provider integration is verified separately. Do not edit manually.\nexport type Json = string | number | boolean | null | { [key:string]: Json | undefined } | Json[];\nexport interface Database { public: { Tables: Record<never,never>; Views: Record<never,never>; Enums: Record<never,never>; CompositeTypes: Record<never,never>; Functions: {\n${result.rows.map((r) => `  ${r.name}: { Args: { ${(r.names || []).map((n, i) => `${n}: ${type(r.types[i])}`).join('; ')} }; Returns: ${type(r.result)} };`).join('\n')}\n} } }\n`;
  await writeFile('src/lib/portal-database.generated.ts', output);
  process.stdout.write(
    `Generated ${result.rows.length} RPC signatures from executed migrations.\n`,
  );
} finally {
  await db.close();
}
